global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: "lgtm-observability"
    environment: "production"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093    # Alertmanager runs on the same server

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["13.61.147.12:9100"]
        labels:
          instance: "app-server"
          environment: "production"

  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "http://localhost:3000"
          - "http://localhost:8000"
          - "http://localhost:9090"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: "blackbox-ssl"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "https://adeshipo-lgtm.duckdns.org"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: "alertmanager"
    static_configs:
      - targets: ["localhost:9093"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["localhost:8889"]

  - job_name: "sample-app"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8000"]
        labels:
          service: "sample-app"
          environment: "production"

  - job_name: "pushgateway"
    honor_labels: true
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9091"]
        labels:
          environment: "production"
