stream_over_http_enabled: true

server:
  http_listen_port: 3200
  log_level:        warn

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

metrics_generator:
  registry:
    external_labels:
      source:  tempo
      cluster: lgtm-production
  storage:
    path: /var/lib/lgtm/tempo/wal
    remote_write:
      - url:           http://127.0.0.1:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local
    local:
      path: /var/lib/lgtm/tempo/traces
    wal:
      path: /var/lib/lgtm/tempo/wal


overrides:
  defaults:
    metrics_generator:
      processors:                [service-graphs, span-metrics]
      generate_native_histograms: both
